theme: minima
title: D.ohnald's
url: "https://dohnald.github.io"
twitter_username: dohnald
github_username: dohnald

markdown: kramdown
#permalink: /blog/:title/

# Collections
collections:
  wiki:
    output: true
    permalink: /blog/:path/
