theme: minima
title: "D.ohnald's"
url: https://dohnald.github.io
twitter_username: dohnald
github_username: dohnald
google_analytics: G-HNGDWZD7FC

markdown: kramdown
highlighter: rouge
#permalink: /blog/:title/

# Collections
collections: 
  wiki: 
    output: true
    permalink: /blog/:path/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

blame: "https://github.com/dohnald/dohnald.github.io/tree/d.ohnald/_wiki"
